---

dependencies: []

galaxy_info:
  author: Nick Lange
  company: Private
  description: Configures Raspberry PI wifi and ensures wifi/bluetooth radios are unblocked via rfkill
  license: MIT
  platforms:
  - name: Debian
    versions:
    - all
  categories:
  - system
